# These are supported funding model platforms


custom:
  [
    "USDT Address (BEP20): 0x871e8d1e2149d6fe5278b379d2e2ec8beebdddeb",
    "EasyPaisa: 03155501381",
    "Bank Account: PK25BAHL2007009500486301, SWIFT: BAHLPKKA, BANK AL HABIB",
  ]
